alkemyTech/OT148-JAVA

- src/main/java/com/alkemy/ong/domain/Role.java
- src/main/java/com/alkemy/ong/mapper/RoleMapper.java
- src/main/java/com/alkemy/ong/repository/RoleRepository.java
- src/main/java/com/alkemy/ong/repository/model/RoleModel.java
Summary
- Role domain added
- RoleModel added
- RoleMapper added
- RoleRepository added
> [Ot148-16] Role creation

- src/main/java/com/alkemy/ong/domain/Member.java
- src/main/java/com/alkemy/ong/mapper/MemberMapper.java
- src/main/java/com/alkemy/ong/repository/MemberRepository.java
- src/main/java/com/alkemy/ong/repository/model/MemberModel.java
Member domain modify
MemberModel modify
MemberMapper modify
MemberRepository modify
> Ot148 22 model repository member

- src/main/java/com/alkemy/ong/domain/Activity.java
- src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
- src/main/java/com/alkemy/ong/repository/ActivityRepository.java
- src/main/java/com/alkemy/ong/repository/model/ActivityModel.java
Fix mistakes OT148-21 Base of Activities
Summary:
The corrections were checked.
Classes fixed
Activity
ActitivityModel
ActivityRepository
ActivityMapper
> OT148 21 Baseofactivities

- src/main/java/com/alkemy/ong/domain/News.java
- src/main/java/com/alkemy/ong/mapper/NewsMapper.java
- src/main/java/com/alkemy/ong/repository/NewsRepository.java
- src/main/java/com/alkemy/ong/repository/model/NewsModel.java
**Summary**
Creation NewsModel
Creation NewsRepository
Creation News (Domain)
Creation NewsMapper
> [OT148-19] News Classes

- src/main/java/com/alkemy/ong/controller/UserController.java
- src/main/java/com/alkemy/ong/mapper/UserMapper.java
- src/main/java/com/alkemy/ong/repository/UserRepository.java
- src/main/java/com/alkemy/ong/repository/model/UserModel.java
- src/main/java/com/alkemy/ong/security/SecurityConfig.java
- src/main/java/com/alkemy/ong/service/UserService.java
- Added endpoint "/users"
Attached test screenshot.
> [OT148-35] Endpoint list users

- src/main/java/com/alkemy/ong/controller/UserController.java
- src/main/java/com/alkemy/ong/dto/ErrorDTO.java
- src/main/java/com/alkemy/ong/dto/UserDTO.java
- src/main/java/com/alkemy/ong/dto/UserUpdateDTO.java
- src/main/java/com/alkemy/ong/exception/UserNotFoundException.java
- src/main/java/com/alkemy/ong/mapper/UserMapper.java
- src/main/java/com/alkemy/ong/security/SecurityConfig.java
- src/main/java/com/alkemy/ong/service/UserService.java
- Added endpoint '/users/id' 
- Added updateUser() method in UserService 
- Added the DTO UserUpdateDTO 
- Added the url '/users/**' in SecurityConfig
Response 404
Response user update
> [OT148-35] Endpoint user update

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/controller/OrganizationController.java
- src/main/java/com/alkemy/ong/dto/OrganizationDTO.java
- src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
- src/main/java/com/alkemy/ong/repository/OrganizationRepository.java
- src/main/java/com/alkemy/ong/service/OrganizationService.java
Summary:
- Create OrganizationController
- Create OrganizationDTO
- Create OrganizationService
- Add method mapDomainToDTO in OrganizationMapper
- Add method findAll in OrganizationRepository
> [Ot148-23]: Endpoint Organization Public Data

- src/main/java/com/alkemy/ong/service/EmailService.java
> add method welcomeEmail

- src/main/resources/application.properties
- Add new property in application properties
> [OT148-99]: DDL Error Schema Creation

- src/main/java/com/alkemy/ong/controller/OrganizationController.java
- src/main/java/com/alkemy/ong/dto/OrganizationUpdateDTO.java
- src/main/java/com/alkemy/ong/exception/OrganizationNotFoundException.java
- src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
- src/main/java/com/alkemy/ong/repository/model/OrganizationModel.java
- src/main/java/com/alkemy/ong/security/SecurityConfig.java
- src/main/java/com/alkemy/ong/service/OrganizationService.java
- src/main/resources/db/migration/V1__init.sql
- src/main/resources/db/migration/V2__insertData.sql
- Added the endpoint "/organization/{id}" in OrganizationController.
- Added updateOrganization() method in OrganizationService.
- Added OrganizationUpdateDTO.
- Added OrganizationNotFoundException.
> [OT148-37] Endpoint update organization

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/controller/OrganizationController.java
- src/main/java/com/alkemy/ong/controller/UserController.java
- src/main/java/com/alkemy/ong/dto/OrganizationUpdateDTO.java
- src/main/java/com/alkemy/ong/dto/UserUpdateDTO.java
- src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
- src/main/java/com/alkemy/ong/mapper/UserMapper.java
- src/main/java/com/alkemy/ong/service/OrganizationService.java
- src/main/java/com/alkemy/ong/service/UserService.java
Amazon S3 integrated with methods that configure images
Sample endpoint responses.
Organization with image.
User with image.
> [OT148-39] Upload images

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/repository/CategoryRepository.java
- src/main/java/com/alkemy/ong/service/CategoryService.java
Summary:
- Added method findAll in CategoryRepository
- Added method getAll in CategoryService
- Added method getAll in CategoryController
> [Ot148-40]: Endpoint Category List

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/exception/CategoryNotFoundException.java
- src/main/java/com/alkemy/ong/service/CategoryService.java
Summary:
- Create CategoryNotFoundException
- Added method getById in CategoryService
- Added methods getById and handleCategoryNotFoundExceptions in CategoryController
> [Ot148-41]: Endpoint Category Details

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/dto/CategoryUpdateDTO.java
- src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
- src/main/java/com/alkemy/ong/service/CategoryService.java
Summary:
- Create CategoryUpdateDTO
- Added method mapUpdateDTOToDomain
- Added method updateCategory in CategoryService
- Added method updateCategory in CategoryController
> [Ot148-43]: Endpoint Category Update

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/controller/NewsController.java
- src/main/java/com/alkemy/ong/service/NewsService.java
- [OT148-48] add deleteNews in ControllerNews
- [OT148-48] add deleteNews in ServiceNews
> Ot148 48 news delete

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/service/CategoryService.java
SUMMARY
Method deleteCategory created  in CategoryService
Endpoint deleteCategory created in CategoryController
> [OT148-44]  Endpoint Delete Categories

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/domain/Contact.java
- src/main/java/com/alkemy/ong/repository/ContactRepository.java
- src/main/java/com/alkemy/ong/repository/model/ContactModel.java
- src/main/java/com/alkemy/ong/service/ContactService.java
- Create Contact domian
- Create ContactModel
- Create ContactRepository
- Create ContactService
> [OT148:53] Contact model and repository

- src/main/java/com/alkemy/ong/controller/ActivityController.java
- src/main/java/com/alkemy/ong/dto/ActivityUpdateDTO.java
- src/main/java/com/alkemy/ong/exception/ActivityNotFoundException.java
- src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
- src/main/java/com/alkemy/ong/service/ActivityService.java
- [OT148-51] create class ActivityUpdateDTO
- [OT148-50] create class ActivityNotFoundException
- [OT148-51] add method mapUpdateDTOToDomain
- [OT148-51] add method updateActivity in activityService
- [OT148-51] add endpoint updateActivity in activityController
> Ot148 51 update activity

- src/main/java/com/alkemy/ong/controller/ContactController.java
- src/main/java/com/alkemy/ong/dto/ContactDTO.java
- src/main/java/com/alkemy/ong/mapper/ContactMapper.java
- src/main/java/com/alkemy/ong/service/ContactService.java
- Create ContactController
- Create ContactMapper
- Create ContactDTO
- Added '/contacts' endpoint
Post success Contact 
Validations
- name null
- email null
> [OT148:54] Endpoint store contacts

- src/main/java/com/alkemy/ong/controller/ContactController.java
- src/main/java/com/alkemy/ong/repository/ContactRepository.java
- src/main/java/com/alkemy/ong/service/ContactService.java
Summary:
- Added method findAll in ContactRepository
- Added method getAll in ContactService
- Added method getAll in ContactController
> [Ot148-61]: Endpoint Contacts List

- src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
Entiendo que no hay que hacer más que esto.
> [OT148-64] Links of social networks in endpoint of organization

- src/main/resources/db/migration/V1__init.sql
- src/main/resources/db/migration/V2__insertData.sql
- [OT148-52] add Create Table Activities
- [OT148-52] data overload activities
> Ot148 52 seed data activity

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/domain/Organization.java
- src/main/java/com/alkemy/ong/domain/Slide.java
- src/main/java/com/alkemy/ong/dto/OrganizationDTO.java
- src/main/java/com/alkemy/ong/dto/SlideDTO.java
- src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
- src/main/java/com/alkemy/ong/mapper/SlideMapper.java
- src/main/java/com/alkemy/ong/repository/SlideRepository.java
- src/main/java/com/alkemy/ong/repository/model/OrganizationModel.java
- src/main/java/com/alkemy/ong/repository/model/SlideModel.java
- src/main/java/com/alkemy/ong/service/OrganizationService.java
- Create SlideDTO
- Modified findAll() method of OrganizationService
Sample changes on the endpoin
t
> [OT148:60] Endpoint slides

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/dto/TestimonialCreationDTO.java
- src/main/java/com/alkemy/ong/dto/TestimonialDTO.java
- src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
- src/main/java/com/alkemy/ong/repository/model/TestimonialModel.java
- src/main/java/com/alkemy/ong/security/SecurityConfig.java
- src/main/java/com/alkemy/ong/service/TestimonialService.java
- src/main/resources/application.properties
Endpoint Creation Testimonial Done
Classes Created
TestimonialController
TestimonialService
TestimonialDTO
TestimonialCreationDTO
Classes Modified
TestimonialMapper
AppConfig
SecurityConfig
> {Ot148 65} Endpoint Creation Testimonial

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/dto/MemberDTO.java
- src/main/java/com/alkemy/ong/mapper/MemberMapper.java
- src/main/java/com/alkemy/ong/repository/MemberRepository.java
- src/main/java/com/alkemy/ong/service/MemberService.java
Summary
Add MemberDTO
Add MemberService
Add MemberController
> [OT148-68] Endpoint members

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/exception/SlideNotFoundException.java
- src/main/java/com/alkemy/ong/service/SlideService.java
- Added SlideController
- Added SlideService
- Added SlideNotFoundException
- Added '/slides/{id}' endpoint in SlideController
Endpoint responses
> [OT148-56] Slides details

- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/service/SlideService.java
- Added endpoint '/slides/id' for delete slide
Endpoint responses
> [OT148-59] Endpoint delete slide

- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/dto/TestimonialUpdateDTO.java
- src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
- src/main/java/com/alkemy/ong/service/TestimonialService.java
Endpoint /testimonials/1 for update testimonials created.
SUMMARY
method testimonialUpdate  created in Service Class
method testimonialUpdate created in Controller Class
method UpdateDTOtoDomain created in MapperClass
TestimonialUpdateDTO  Class created.
Running Project Checked
> TestimonialUpdateDone

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/domain/Organization.java
- src/main/java/com/alkemy/ong/dto/SlideCreationDTO.java
- src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
- src/main/java/com/alkemy/ong/mapper/SlideMapper.java
- src/main/java/com/alkemy/ong/repository/SlideRepository.java
- src/main/java/com/alkemy/ong/service/SlideService.java
- src/main/java/com/alkemy/ong/util/Base64DecodedMultiPartFile.java
Summary:
- Created class SlideCreationDTO
- Created class Base64DecodedMultiPartFile
- Changes to methods in SlideMapper
- Changes to slideService in AppConfig
- Added method findFirstByOrganization_IdOrderByOrganizationOrderDesc in SlideRepository
- Added methods createSlide, decodeImage and uploadImage in SlideService
- Added method createSlide in SlideController
> [Ot148-57]: Endpoint Slides Creation

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/service/ContactService.java
- src/main/java/com/alkemy/ong/service/EmailService.java
- src/main/resources/template/plantilla_email_contacto.html
Summary:
- Created html plantilla_email_contacto
- Added emailTemplateContact and change emailService method in AppConfig
- Added method greetingsContact and update constructor in EmailService
- Added use of greetingsContact in method addContact and update constructor in ContactService
> [Ot148-62]: Email Send Contact

- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/dto/SlideUpdateDTO.java
- src/main/java/com/alkemy/ong/mapper/SlideMapper.java
- src/main/java/com/alkemy/ong/service/SlideService.java
Summary:
- Created SlideUpdateDTO
- Added method mapUpdateDTOToDomain in SlideMapper
- Added method updateSlide in SlideService
- Added method updateSlide in SlideController
> [Ot148-58]: Endpoint Slides Update

- src/main/java/com/alkemy/ong/security/SecurityConfig.java
Summary:
- Added use of hasAnyAuthority for endpoints in AppConfig
> [OT148-33]: Role Validate

- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/repository/SlideRepository.java
- src/main/java/com/alkemy/ong/service/SlideService.java
- [OT148-55] add method getAll in SlideService
- [OT148-55] Add getAll in SlideController
> Ot148 55 slide list

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/controller/UserController.java
- src/main/java/com/alkemy/ong/exception/DuplicateEmailException.java
- src/main/java/com/alkemy/ong/service/UserService.java
- [OT148-49] add token return on sign up
- [OT148-49] add validation existEmail
> Ot148 49 token register

- README.md
- pom.xml
- src/main/java/com/alkemy/ong/config/SwaggerConfig.java
- src/main/java/com/alkemy/ong/controller/SwaggerController.java
- src/main/java/com/alkemy/ong/security/SecurityConfig.java
- Added config Swagger
- Added '/api/docs' endpoint 
Swagger on
> [OT148:84] Swagger

- src/main/java/com/alkemy/ong/controller/CommentController.java
- src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
- src/main/java/com/alkemy/ong/dto/CommentBodyDTO.java
- src/main/java/com/alkemy/ong/mapper/CommentMapper.java
- src/main/java/com/alkemy/ong/repository/CommentRepository.java
- src/main/java/com/alkemy/ong/repository/model/CommentModel.java
- src/main/java/com/alkemy/ong/security/SecurityConfig.java
- src/main/java/com/alkemy/ong/service/CommentService.java
- Added CommentController interface
- Added CommentResource what implement CommentController
- Added url '/comments' to SecurityConfig
- Added '/comments' endpoint
Show response
> [OT148-75] Endpoint get comments

- src/main/java/com/alkemy/ong/controller/CommentController.java
- src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
- src/main/java/com/alkemy/ong/exception/CommentNotFoundException.java
- src/main/java/com/alkemy/ong/security/SecurityConfig.java
- src/main/java/com/alkemy/ong/service/CommentService.java
Summary:
- Created class CommentNotFoundException
- Added method deleteComment in CommentService
- Added method deleteComment in CommentController
- Added method deleteComment in CommentResource
- Updated SecurityConfig
> [Ot148-78]: Endpoint Comment Delete

- src/main/java/com/alkemy/ong/config/AppConfig.java
- src/main/java/com/alkemy/ong/controller/CommentController.java
- src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
- src/main/java/com/alkemy/ong/dto/CommentCreationDTO.java
- src/main/java/com/alkemy/ong/mapper/CommentMapper.java
- src/main/java/com/alkemy/ong/security/MainUser.java
- src/main/java/com/alkemy/ong/security/SecurityConfig.java
- src/main/java/com/alkemy/ong/service/CommentService.java
- Added '/comments' endpoint for creation Comment
- Added createComment() method in CommentService
- Added CommentCreationDTO in dto
Show responses
> [OT148-76] Creation comment

- src/main/java/com/alkemy/ong/controller/CommentController.java
- src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
- src/main/java/com/alkemy/ong/dto/CommentBodyDTO.java
- src/main/java/com/alkemy/ong/exception/OperationNotPermitted.java
- src/main/java/com/alkemy/ong/exception/OperationNotPermittedException.java
- src/main/java/com/alkemy/ong/mapper/CommentMapper.java
- src/main/java/com/alkemy/ong/security/SecurityConfig.java
- src/main/java/com/alkemy/ong/security/SecurityUtils.java
- src/main/java/com/alkemy/ong/service/CommentService.java
- Added POST '/comments/{id}' endpoint in CommentController
- Added updateComment() method in CommentService
Show responses
> OT148-77: Update Comment

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/dto/PageDTO.java
- src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
- src/main/java/com/alkemy/ong/repository/CategoryRepository.java
- src/main/java/com/alkemy/ong/service/CategoryService.java
- [OT148-80] modify to findAllPage with a size of 10 categories
- [OT148-80] modified method findAll
- [OT148-80] modified CrudRepository to JpaRepository
> Ot148 80 pagination category

- pom.xml
- src/main/java/com/alkemy/ong/controller/UserController.java
- src/main/java/com/alkemy/ong/controller/impl/UserResource.java
- Added documentation to authentication endpoints
- Change UserController to interface
- Added UserResource
> [OT148-89] Authentication documentation

- src/main/java/com/alkemy/ong/controller/ActivityController.java
- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/controller/ContactController.java
- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/controller/NewsController.java
- src/main/java/com/alkemy/ong/controller/OrganizationController.java
- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/controller/impl/ActivityResource.java
- src/main/java/com/alkemy/ong/controller/impl/CategoryResource.java
- src/main/java/com/alkemy/ong/controller/impl/ContactResource.java
- src/main/java/com/alkemy/ong/controller/impl/MemberResource.java
- src/main/java/com/alkemy/ong/controller/impl/NewsResource.java
- src/main/java/com/alkemy/ong/controller/impl/OrganizationResource.java
- src/main/java/com/alkemy/ong/controller/impl/SlideResource.java
- src/main/java/com/alkemy/ong/controller/impl/TestimonialResource.java
- Changed controllers classes to interfaces.
- The resource classes that implement the interfaces of the controllers were added.
> [OT148-100] Changes various controllers

- src/main/java/com/alkemy/ong/controller/CommentController.java
- src/main/java/com/alkemy/ong/controller/impl/CommentResource.java
- src/main/java/com/alkemy/ong/repository/CommentRepository.java
- src/main/java/com/alkemy/ong/security/SecurityConfig.java
- src/main/java/com/alkemy/ong/service/CommentService.java
- [OT148-79] add antmatchers to list comments of a post
- [OT148-79] add method getAllComment
- [OT148-79] add Get findAllComment
- [OT148-79] add findAllComment development
> Ot148 79 list comment

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/controller/impl/CategoryResource.java
- [OT148-85] documentation swagger Category
> Ot148 85 documentation categories

- src/main/java/com/alkemy/ong/controller/NewsController.java
- src/main/java/com/alkemy/ong/controller/impl/NewsResource.java
Summary:
- Changed NewsController class to interface and created NewsResource class. Added Swagger documentation to NewsController.
> [OT148-86]: Add News Documentation

- pom.xml
- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/controller/impl/TestimonialResource.java
SUMMARY
Testimonial Controller has become  in an interface
Testimonial Resource has been created and implement the firts one.
EVIDENCE
> {Ot148 88} Add Documentation Testimonials

- src/main/java/com/alkemy/ong/dto/JwtDTO.java
- src/main/java/com/alkemy/ong/service/UserService.java
Remove authorities from the Response JWT
JwtDTO modified
UserService modified
> RemoveAuthorities

- src/test/java/com/alkemy/ong/MemberControllerFunctionalTest.java
- src/test/java/com/alkemy/ong/util/HeaderBuilder.java
- src/test/java/com/alkemy/ong/util/JwtUtil.java
- src/test/resources/application-test.properties
Voy subiendo el PR con un test por método de CRUD.
Están incluidos los archivos Util y properties.
Luego subo más tests.
Por separado me funcionan todos...pero cuando testeo la clase me larga error en el de Delete.
> [OT148-91] Test: Endpoint/members

- src/main/java/com/alkemy/ong/controller/UserController.java
- src/main/java/com/alkemy/ong/controller/impl/UserResource.java
- src/main/java/com/alkemy/ong/exception/WrongValuesException.java
- src/main/java/com/alkemy/ong/service/UserService.java
Summary:
- Created class WrongValuesException
- Updated use of WrongValuesException in UserService, UserController and UserResource
> [OT148-103]: Fix User Login Exception

- src/test/java/com/alkemy/ong/UserControllerFuncionalTest.java
> [OT148-96] Test endpoint authentication

- src/test/java/com/alkemy/ong/CommentControllerFunctionalTest.java
Summary:
- Created test class CommentControllerFunctionalTest
> [OT148-102]: Test Endpoint Comments

- src/main/java/com/alkemy/ong/controller/OrganizationController.java
- src/main/java/com/alkemy/ong/repository/model/OrganizationModel.java
- src/test/java/com/alkemy/ong/OngControllerFunctionalTest.java
- src/test/java/com/alkemy/ong/OrganizationControllerFunctionalTest.java
- [OT148-92] create class OngControllerTest and add methods
- [OT148-92] modified method updateOrganization
> Ot148 92 test ong

- README.md
- [OT148-105] add information in readme
> [OT148-105] add information in readme

- src/main/java/com/alkemy/ong/controller/TestimonialController.java
Summary: 
Added a Description to Testimonials
> [OT148]: Added a Description to Testimonials

- src/main/java/com/alkemy/ong/controller/OrganizationController.java
- src/main/java/com/alkemy/ong/controller/impl/OrganizationResource.java
Summary:
- Added swagger documentation to OrganizationController and OrganizationResource
> [OT148]: Added Organizations Documentation

- src/main/java/com/alkemy/ong/controller/ContactController.java
- src/main/java/com/alkemy/ong/controller/NewsController.java
- src/main/java/com/alkemy/ong/controller/impl/ContactResource.java
- [OT148] modified description to NewsController
- [OT148] add swagger in Comments
> Ot148 documentation comments

- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/controller/impl/SlideResource.java
Slide Resource Modified for add Documentation
>  [148] Added Slides Documentation
